Кравченко Юлии ПИ19-4
Вариант 12 

Задание 7. Транспортная задача

A1, A2, A3 – поставщики с запасами a1, a2, a3 однородного
груза, B1, B2, B3, B4, B5 – потребители с потребностями b1, b2, b3, b4, b5. Матрица тарифов
C = (cij ), где i = 1, 2, 3 и j = 1, 2, 3, 4, 5, содержит стоимости перевозки единицы груза
из пункта Ai в пункт Bj
.

In [16]:
# Загрузим необходимые библиотеки
import numpy as np
from scipy.optimize import linprog
import warnings
warnings.filterwarnings('ignore')
          

In [17]:
a = np.array([270, 390, 250]) # Запасы по складам
b = np.array([160, 110, 210, 280, 150]) #Потребности
# Матрица тарифов
C = np.array([[12, 10, 6, 10, 4],
              [13, 12, 5, 15, 7],
              [8, 9, 15, 17, 26]])  

Метод Северо-западного угла:

In [18]:
def Transport_severo_zapad(a_, b_, c_):
    a = np.copy(a_)
    b = np.copy(b_)
    c = np.copy(c_)
    
    # Проверяем условие замкнутости:
    if a.sum() > b.sum():
        b = np.hstack((b, [a.sum() - b.sum()]))
        c = np.hstack((c, np.zeros(len(a)).reshape(-1, 1)))
    elif a.sum() < b.sum():
        a = np.hstack((a, [b.sum() - a.sum()]))
        c = np.vstack((c, np.zeros(len(b))))
        
    m = len(a)
    n = len(b)
    i = 0
    j = 0
    funk = 0
    x = np.zeros((m, n), dtype=int)
    while (i<m) and (j<n): # повторяем цикл до сходимости метода
        x_ij = min(a[i], b[j]) # проверяем минимальность a_i и b_j
        funk += c[i, j]*min(a[i], b[j]) 
        a[i] -= x_ij 
        b[j] -= x_ij 
        x[i, j] = x_ij 
    
        if a[i]>b[j]: # делаем сдвиги при выполнении условий
            j += 1
        elif a[i]<b[j]:
            i += 1
        else:
            i += 1
            j += 1
    return x, funk 

In [19]:
x1, funk1 = Transport_severo_zapad(a, b, C)
print('Метод северо-западного угла: \n', x1)
print('Оптимальная стоимость перевозки: ', funk1)


Метод северо-западного угла: 
 [[160 110   0   0   0]
 [  0   0 210 180   0]
 [  0   0   0 100 150]]
Оптимальная стоимость перевозки:  12370
