Кравченко Юлии ПИ19-4 

Вариант 80

In [1]:
import scipy
from scipy.optimize import linprog 
import numpy as np
import pandas as pd

Задание 1

In [10]:
a = np.array([70, 50, 240]) # Запасы по складам
b = np.array([100, 10, 70, 160]) #Потребности
# Матрица тарифов
C = np.array([[16, 18, 9, 1],
              [13, 16, 18, 9],
              [14, 23, 12, 7]])

In [14]:
def Transport_severo_zapad(a, b, c):
    
    # Проверяем условие замкнутости:
    if a.sum() > b.sum():
        b = np.hstack((b, [a.sum() - b.sum()]))
        c = np.hstack((c, np.zeros(len(a)).reshape(-1, 1)))
    elif a.sum() < b.sum():
        a = np.hstack((a, [b.sum() - a.sum()]))
        c = np.vstack((c, np.zeros(len(b))))
        
    m = len(a)
    n = len(b)
    i = 0
    j = 0
    funk = 0
    x = np.zeros((m, n), dtype=int)
    while (i<m) and (j<n): # повторяем цикл до сходимости метода
        x_ij = min(a[i], b[j]) # проверяем минимальность a_i и b_j
        funk += c[i, j]*min(a[i], b[j]) 
        a[i] -= x_ij 
        b[j] -= x_ij 
        x[i, j] = x_ij 
    
        if a[i]>b[j]: # делаем сдвиги при выполнении условий
            j += 1
        elif a[i]<b[j]:
            i += 1
        else:
            i += 1
            j += 1
    return x, funk 

In [15]:
x1, funk1 = Transport_severo_zapad(a, b, C)
print('Метод северо-западного угла: \n', x1)
print('Оптимальная стоимость перевозки: ', funk1)

Метод северо-западного угла: 
 [[ 70   0   0   0   0]
 [ 30  10  10   0   0]
 [  0   0  60 160  20]]
Оптимальная стоимость перевозки:  3690.0


Задание 3

In [5]:
c = [-1,-1] # список коэффициентов функции цели
b_ub = [1,1,1] 
A_ub = [[14,5],
        [6,10],
        [15,2]]
d=linprog(c, A_ub, b_ub,method='simplex' ) 
print(d)
print("Цена игры:",1/d.x.sum())
y1 = d.x[0]/d.x.sum()
y2 = d.x[1]/d.x.sum()
#y3 = d.x[2]/d.x.sum()
print("X* =",(y1,y2),"-оптимальная стратегия  I игрока ")

     con: array([], dtype=float64)
     fun: -0.11818181818181817
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([1.11022302e-16, 0.00000000e+00, 1.72727273e-01])
  status: 0
 success: True
       x: array([0.04545455, 0.07272727])
Цена игры: 8.461538461538463
X* = (0.38461538461538464, 0.6153846153846154) -оптимальная стратегия  I игрока 


Задание №2

In [20]:
A = [[3,5,6,2],
[3,-1,8,4],
[-4,3,7,-2],
[9,5,6,5],
[-3,6,8,4]]

##Критерий Сэвиджа
ss = np.array(A)
    #print(ss)

m = 5
n = 4
ss1 = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        ss1[i,j] = int(ss[i,j])
            #ss1 = map(int, ss)
        #print(ss1)
        c_min21 = (ss1[:,0].max()-ss1[:,0])
        c_min22 = (ss1[:,1].max()-ss1[:,1])
        c_min23 = (ss1[:,2].max()-ss1[:,2])
        c_min24 = (ss1[:,3].max()-ss1[:,3])

sevid = pd.DataFrame((c_min21,c_min22,c_min23,c_min24))
sevid_transposed = sevid.T    
    #print(sevid_transposed)
qwe = sevid_transposed.max(axis=1)
SEVID_df4 = pd.DataFrame(qwe)
SEVID_df4a = SEVID_df4.rename(index={0: "A1", 1: "A2", 2: "A3",3:"A4"})
print(SEVID_df4a)
sev_str = SEVID_df4a[SEVID_df4a[0]==SEVID_df4a[0].min()]
print("4) Оптимальная стратегия игрока А по критерию Сэвиджа и Величина минимальной недополученной прибыли по критерию Сэвиджа:", sev_str)



       0
A1   6.0
A2   7.0
A3  13.0
A4   2.0
4   12.0
4) Оптимальная стратегия игрока А по критерию Сэвиджа и Величина минимальной недополученной прибыли по критерию Сэвиджа:       0
A4  2.0
